This Notebook will import an NFT Similarity Matrix and also a dataframe containing a list of users who have purchased an NFT collection in the past. We will then use these information to train out model following these steps :<br>
<br>
1) Get the Name of an NFT collection and use the cosine similarity matrix to get a list of collections which we deem are "simillar" <br><br>
2) Get the list of wallet addresses which have purchased the NFT collection in the past. <br><br>
3) Then use the Alchemy NFT API endpoint to get a list of nft collections that this user owns. If the user owns any of the following recommended NFT collections, increase the similairty score in the similarity matrix by a lot. If the User does not own a recommended NFT collection, decrease the similality score by a small amount. We provide a large bonus for correct recommendations and a small penaltiy for false recommendations because it is much much more likley that a user does not own a recommended NFT than a does own a recommened NFT

In [128]:
#Import the Neccessary Libraries
import numpy as np
import pandas as pd

In [129]:
Collection_Addresses = pd.read_csv('OpenseaData/OpenSeaSalesDataRightFormat_csv.csv', error_bad_lines=False)

In [130]:
#Import necessarry dataframes
similarity_data_frame = pd.read_csv('OpenseaData/CosineSimilairtyDataFrame_csv.csv', error_bad_lines=False)
#similarity_data_frame = similarity_data_frame.set_index('Collections')

In [131]:
address_to_collections = pd.read_csv('OpenseaData/address_to_collections.csv', error_bad_lines=False)

In [132]:
#Now creating a function which will return a list of recommendations
def getRecommendations(input_collection_name, output_size):
    scores = list(enumerate(similarity_data_frame[input_collection_name]))
    scores_sorted = sorted(scores, key=lambda x:x[1], reverse=True)
    
    j = 1
    output_array = []
    for i in range(0, output_size):
        collection_name = similarity_data_frame.iloc[scores_sorted[i][0]].values[0]
        if collection_name != input_collection_name:
            output_array.append(collection_name)
            j+=1
    return output_array

In [133]:
crypto_punk_output = getRecommendations("CryptoPunks", 10)
crypto_punk_output

['FLUF World',
 'Cryptoadz',
 'CyberBrokers',
 'Aurory',
 'Hashmasks',
 'Animetas',
 'Acrocalypse',
 '0N1 Force',
 'Emblem Vault']

In [32]:
# Example of a single training set : 0xa00e47c8fbe274ab3c24b08081d661c8536bc80c
NFTs_0xa00e47c8fbe274ab3c24b08081d661c8536bc80c = ['10 Most Influential in Blockchain 2018 presented by CoinDesk', 'CheezeWizard', 
                                                  "Writer's Room: Valet Ticket", "Based Ghouls", "Neon District", "Ethmoji", "MoonBase"]

In [31]:
Collection_Addresses.head()

,asset.collection.name,winner_account.address
0,10 Most Influential in Blockchain 2018 present...,"['0xa00e47c8fbe274ab3c24b08081d661c8536bc80c',..."
1,BlockchainCuties,"['0x5aeb1fcb423e89f5258bb653569aa671aa68f6e6',..."
2,CaesarsTriumph,"['0xee8eeec3e7a5ad82827480a9e00d01b1ec0a9f3b',..."
3,Chibi Fighters 1.0,"['0x7977664f1786f4621750f1d4d7fec578ca59912d',..."
4,CryptoAssault,"['0xf7ee6c2f811b52c72efd167a1bb3f4adaa1e0f89',..."

In [37]:
address_to_collections.head()

,winner_account.address,asset.collection.name
0,0x000000aaee6a496aaf7b7452518781786313400f,['Mythereum']
1,0x0002fd0f1d0708fdf065d3625b2ee83d210d58d9,"['MyCryptoHeroes', 'MyCryptoHeroes', 'MyCrypto..."
2,0x0008d343091ef8bd3efa730f6aae5a26a285c7a2,"['Ethermon', 'Ethermon', 'Ethermon', 'Ethermon..."
3,0x000b75fcdc15d41277deb033c72d2c8d774ccced,"['CryptoAssault', 'CryptoAssault', 'CryptoAssa..."
4,0x0013d759a369091f3d2d1d1a516adaf068f67923,"['CryptoAssault', 'CryptoAssault']"

In [44]:
# 0x0008d343091ef8bd3efa730f6aae5a26a285c7a2
address_to_collections['winner_account.address'][2]
index_2_collections = address_to_collections['asset.collection.name'][2]
index_2_collections

"['Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon', 'Ethermon']"

In [45]:
# 0x0008d343091ef8bd3efa730f6aae5a26a285c7a2
address_to_collections['winner_account.address'][4]
index_2_collections = address_to_collections['asset.collection.name'][4]
index_2_collections

"['CryptoAssault', 'CryptoAssault']"

In [134]:
User1 = ['NBA Top Shot', 'The Sandbox', 'Imaginary Ones', 'Pixel Vault Founders DAO']

In [135]:
User1_0_rec = getRecommendations(User1[0], 40)
User1_0_rec

['Otherdeed',
 'Doodles',
 'Meebits',
 'Sorare',
 'DeadFellaz',
 'ALIENFRENS',
 'Axie Infinity',
 'Art Blocks',
 'The Sandbox',
 'Farmers World',
 'ZED RUN',
 'NFT Worlds',
 'Cool Pets',
 'Creature World NFT',
 'Ethereum Name Service',
 'MURI',
 'Bored Ape Yacht Club',
 'Mutant Ape Yacht Club',
 'VeeFriends Series 2',
 'Tubby Cats',
 'Panini America',
 'Azuki',
 'CloneX',
 'Moonbirds',
 'Crabada',
 'MFER',
 'projectPXN',
 'LOSTPOETS',
 '3Landers',
 'goblintown',
 'Adam Bomb Squad',
 'Gods Unchained Immutable',
 'NFL All Day',
 'Cool Cats',
 'Pudgy Penguins',
 'Okay Bears',
 'Lazy Lions',
 'Alien Worlds',
 'Mooncats']

In [136]:
missing_penalty = -0.000001
having_bonus = 0.001

In [137]:
user1_nft_set = set(User1)
user1_nft_set

{'Imaginary Ones', 'NBA Top Shot', 'Pixel Vault Founders DAO', 'The Sandbox'}

In [138]:
similarity_data_frame.head()

,Collections,Axie Infinity,Bored Ape Yacht Club,CryptoPunks,Mutant Ape Yacht Club,Art Blocks,Otherdeed,NBA Top Shot,Azuki,CloneX,...,CryptoonGoonz,Deafbeef,Illuminati,Bastard Gan Punks V2,Fishy Fam,Potatoz,Mindblowon,Sipherian Surge,Wool Pouch,Los Muertos
0,Axie Infinity,1.000000,0.577350,0.182574,0.577350,0.666667,0.730297,0.617213,0.547723,0.547723,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.182574,0.000000,0.000000,0.166667
1,Bored Ape Yacht Club,0.577350,1.000000,0.158114,0.875000,0.577350,0.632456,0.534522,0.474342,0.474342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.158114,0.000000,0.000000,0.144338
2,CryptoPunks,0.182574,0.158114,1.000000,0.158114,0.182574,0.200000,0.169031,0.200000,0.400000,...,0.4,0.0,0.4,0.0,0.182574,0.2,0.200000,0.365148,0.182574,0.182574
3,Mutant Ape Yacht Club,0.577350,0.875000,0.158114,1.000000,0.577350,0.632456,0.534522,0.474342,0.474342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.158114,0.000000,0.000000,0.144338
4,Art Blocks,0.666667,0.577350,0.182574,0.577350,1.000000,0.730297,0.617213,0.547723,0.547723,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.182574,0.000000,0.000000,0.166667

In [139]:
similarity_training_data_frame = similarity_data_frame.set_index('Collections')

In [140]:
similarity_training_data_frame.head()

,Axie Infinity,Bored Ape Yacht Club,CryptoPunks,Mutant Ape Yacht Club,Art Blocks,Otherdeed,NBA Top Shot,Azuki,CloneX,Moonbirds,...,CryptoonGoonz,Deafbeef,Illuminati,Bastard Gan Punks V2,Fishy Fam,Potatoz,Mindblowon,Sipherian Surge,Wool Pouch,Los Muertos
Collections,,,,,,,,,,,,,,,,,,,,,
Axie Infinity,1.000000,0.577350,0.182574,0.577350,0.666667,0.730297,0.617213,0.547723,0.547723,0.547723,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.182574,0.000000,0.000000,0.166667
Bored Ape Yacht Club,0.577350,1.000000,0.158114,0.875000,0.577350,0.632456,0.534522,0.474342,0.474342,0.474342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.158114,0.000000,0.000000,0.144338
CryptoPunks,0.182574,0.158114,1.000000,0.158114,0.182574,0.200000,0.169031,0.200000,0.400000,0.400000,...,0.4,0.0,0.4,0.0,0.182574,0.2,0.200000,0.365148,0.182574,0.182574
Mutant Ape Yacht Club,0.577350,0.875000,0.158114,1.000000,0.577350,0.632456,0.534522,0.474342,0.474342,0.474342,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.158114,0.000000,0.000000,0.144338
Art Blocks,0.666667,0.577350,0.182574,0.577350,1.000000,0.730297,0.617213,0.547723,0.547723,0.547723,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.182574,0.000000,0.000000,0.166667

In [141]:
for i in range(0, len(User1_0_rec)):
    if User1_0_rec[i] in user1_nft_set:
        print("In user set")
        similarity_training_data_frame[User1_0_rec[i]][User1[0]] = similarity_training_data_frame[User1_0_rec[i]][User1[0]] + having_bonus
        similarity_training_data_frame[User1[0]][User1_0_rec[i]] = similarity_training_data_frame[User1[0]][User1_0_rec[i]] + having_bonus
    else:
        print("Not in user set")
        similarity_training_data_frame[User1_0_rec[i]][User1[0]] = similarity_training_data_frame[User1_0_rec[i]][User1[0]] + missing_penalty
        similarity_training_data_frame[User1[0]][User1_0_rec[i]] = similarity_training_data_frame[User1[0]][User1_0_rec[i]] + missing_penalty

Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
In user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set

Made two similarity dataframes. One for the Training and one for getting the recommendations

In [147]:
def Unit_Train(User1, similarity_training_data_frame, User1_0_rec, user1_nft_set):
    for i in range(0, len(User1_0_rec)):
        if User1_0_rec[i] in user1_nft_set:
            print("In user set")
            similarity_training_data_frame[User1_0_rec[i]][User1[0]] = similarity_training_data_frame[User1_0_rec[i]][User1[0]] + having_bonus
            similarity_training_data_frame[User1[0]][User1_0_rec[i]] = similarity_training_data_frame[User1[0]][User1_0_rec[i]] + having_bonus
        else:
            print("Not in user set")
            similarity_training_data_frame[User1_0_rec[i]][User1[0]] = similarity_training_data_frame[User1_0_rec[i]][User1[0]] + missing_penalty
            similarity_training_data_frame[User1[0]][User1_0_rec[i]] = similarity_training_data_frame[User1[0]][User1_0_rec[i]] + missing_penalty
    return similarity_training_data_frame

In [148]:
user2 = ['Jungle Freaks', 'Rug Radio - Genesis NFT', 'Blitmap', 'Bloot']
user2_set = set(user2)
user2_recs = getRecommendations(user2[0], 40)
similarity_training_data_frame = Unit_Train(user2, similarity_training_data_frame, user2_recs, user2_set)

Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
In user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set
Not in user set

In [153]:
def Test_Metric(user_nfts_set, user_recommendations):
    correct_count = 0
    wrong_count = 0
    for i in range(0, len(user_recommendations)):
        if user_recommendations[i] in user_nfts_set:
            correct_count = correct_count + 1
        else:
            wrong_count = wrong_count + 1
    return (correct_count, wrong_count)

In [154]:
test_output = Test_Metric(user2_set, user2_recs)
print("Correct : " + str(test_output[0]))
print("Wrong : " + str(test_output[1]))

Correct : 1
Wrong : 38